var phrase = [
  '] <strong>Press <font color="#f4f2af">F1</font></strong> For ] HELP',
  '"Do NOT play <a href="https://www.roblox.com/games/2809844442/Midnight-Horrors"><font color="red">Midnight Horrors</font></a> at 3AM. WORST mistake of my life."',
  "no",
  '"Use the <a onclick="openPop(\'assets/secretfairycode.png\')"/><font color="#d8bc42">Fairy Seeking-Spell</font></a>. <font color="#f4f2af"><strong>Using your arrow keys</strong></font>, tiny false faries will be drawn along the fold to reveal the <font color="#208bbb">true secret</font>."',
  '"Use the <a onclick="openPop(\'assets/secretfairycode.png\')"/><font color="#d8bc42">Fairy Seeking-Spell</font></a>. <font color="#f4f2af"><strong>Using your arrow keys</strong></font>, tiny false faries will be drawn along the fold to reveal the <font color="#208bbb">true secret</font>."',
  '"Use the <a onclick="openPop(\'assets/secretfairycode.png\')"/><font color="#d8bc42">Fairy Seeking-Spell</font></a>. <font color="#f4f2af"><strong>Using your arrow keys</strong></font>, tiny false faries will be drawn along the fold to reveal the <font color="#208bbb">true secret</font>."',
  '"Use the <a onclick="openPop(\'assets/secretfairycode.png\')"/><font color="#d8bc42">Fairy Seeking-Spell</font></a>. <font color="#f4f2af"><strong>Using your arrow keys</strong></font>, tiny false faries will be drawn along the fold to reveal the <font color="#208bbb">true secret</font>."',
  '"Use the <a onclick="openPop(\'assets/secretfairycode.png\')"/><font color="#d8bc42">Fairy Seeking-Spell</font></a>. <font color="#f4f2af"><strong>Using your arrow keys</strong></font>, tiny false faries will be drawn along the fold to reveal the <font color="#208bbb">true secret</font>."',
  '"Use the <a onclick="openPop(\'assets/secretfairycode.png\')"/><font color="#d8bc42">Fairy Seeking-Spell</font></a>. <font color="#f4f2af"><strong>Using your arrow keys</strong></font>, tiny false faries will be drawn along the fold to reveal the <font color="#208bbb">true secret</font>."',
  '"Use the <a onclick="openPop(\'assets/secretfairycode.png\')"/><font color="#d8bc42">Fairy Seeking-Spell</font></a>. <font color="#f4f2af"><strong>Using your arrow keys</strong></font>, tiny false faries will be drawn along the fold to reveal the <font color="#208bbb">true secret</font>."',
  '"Use the <a onclick="openPop(\'assets/secretfairycode.png\')"/><font color="#d8bc42">Fairy Seeking-Spell</font></a>. <font color="#f4f2af"><strong>Using your arrow keys</strong></font>, tiny false faries will be drawn along the fold to reveal the <font color="#208bbb">true secret</font>."',
  '"Use the <a onclick="openPop(\'assets/secretfairycode.png\')"/><font color="#d8bc42">Fairy Seeking-Spell</font></a>. <font color="#f4f2af"><strong>Using your arrow keys</strong></font>, tiny false faries will be drawn along the fold to reveal the <font color="#208bbb">true secret</font>."',
  '"Use the <a onclick="openPop(\'assets/secretfairycode.png\')"/><font color="#d8bc42">Fairy Seeking-Spell</font></a>. <font color="#f4f2af"><strong>Using your arrow keys</strong></font>, tiny false faries will be drawn along the fold to reveal the <font color="#208bbb">true secret</font>."',
  '"<font color="#faec4f">Wooow, my head\'s spinning!</font>"',
  '"<font color="#f4f2af">Up, Up, Down, Down, Left, Right, Left, Right...</font> I don\'t remember the rest!"',
  "Hi, I'm Saul Goodman. Did you know that you have rights? The constitution says you do, and so do I.",
  "You're gonna be recompleted.",
  "I am Heisenberg",
  "Way to go superstar! I knew you could do it!",
  "Squares are bad news, man. Stay away from 'em, kids!",
  '"A human in my furry game?"',
  '"<font color="#bb2e1d">Why did you make me do this? You\'re fighting so you can watch everyone around you die!</font>"',
  '"No copyright law in the universe is going to stop me!"',
  "Hey guys, did you know that in terms of male human and female Pokémon breeding, Vaporeon is the most-",
  "Nintendo has games.",
  "What if we kissed in/at the-",
  '"Hi, after a manual review, a copyright owner has claimed some material in your video."',
  "Human!!!",
  '"They say there is a person who will tell you how to survive in this land... oh wait. That\'s me."',
  "An update to Team Fortress 2 has been released. The update will be applied automatically when you restart Team Fortress 2. The major changes include:",
  "Further improvements to overall system stability and other minor adjustments have been made to enhance the user experience.",
  "Absolutely!",
  '"I just need to find a team and stop solo queuing."',
  "Fair and Balanced.",
  '<a href="https://www.youtube.com/watch?v=GJWdCL-obXU" target="_blank">THIS IS ROCKET LEAGUE!</a>',
  "It's not a bug, it's a feature!",
  "What's wrong with you?",
  "I have two sides",
  "What if God said-",
  "Pablo",
  '"Subarashii"',
  '"Nothing is more American than killing a man in this Walmart of a world"',
  '"<font color="#f07d00">Post a new question. Get an expert answer within hours!</font>"',
  '"You have pending course evaluations"',
  "Little baby man.",
  "Beep bo bap bop",
  '<a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" target="_blank"><font color="white">https://www.youtube.com/watch?v=dQw4w9WgXcQ</font></a>',
  "I think I smell a barbecue!",
  '"Prank em John"',
  '"Ayo the pizza\'s here!"',
  "Around the world, around the world. Around the world, around the world. Around the world, around the world. Around the world, around the world. Around the world, around the world. Around the world, around the world. Around the world, around the world.",
  "dab me up",
  "One more time. One more time. One more time, we're gonna celebrate. Oh yeah, alright, don't stop the dancing. One more time, we're gonna celebrate. Oh yeah, alright, don't stop the dancing",
  '"<font color="#ee9ea0">He\'s just standing there. MENACINGLY!</font>"',
  "Maria.",
  '<font color="red">Doctors Hate Him!</font> Saving the ones you love with this ONE WEIRD TRICK!',
  '"Bri\'ish"',
  '"OMG! It\'s Korn. <font size="17">ᛁᛊⳖᚪᛜᛢᛁᚧⳘᚪⳖᛢⳖᚱᛒᚧᛜⰞᛁᛈⳘᛢⲔᛊᛒᚪⳖᚧᛁⰞⲔᛒᚪᛜᚧᛜⰞᛒᚪᛁᛈᛜᛢᚢᚱᛒᚪᛜᛈᛜᛢᚢᛊᛒᚧᛜᚧⲔᛢᚢᛊᚱᛒᚺᚪᛁᛢⲔᛊᚢᚪᚺᚪᛜⲔᛢᚢᚧ ᚧᛜᛈⲔⲔᛢᚢᚾⳖᚪᛁᚪⲔᚷⲔᛊᚢᚪᛒᛈᛁⲔᚧᚢᛊᛒᚳⰞᚳᚷⳘꓦᚺᛈⳘꓦᛉᛒᚾᚢᚱᚱᛁᛊⲔᚷⳖꓦᛉᚪⳖᚧⳖᚳᚣᛁᚱᛁꓦᛁꓦⲔᛢᚢᚪ ᛈⲔᛁᛈᛁᚧⲔᛢⲔᛢⳖᚪᚢᚪᛒᚪᛒⳖᛩᛁᛈⲔᚧⲔᛢⳖᚱᛒᛩⳖꓦᛁꓦᛜᚧⲔᚧᛒᚾᚺᚱⳖᚪᛁᛈⳘᛒᚾᛒᚱᚱᚢᚧᚱᛈᛁᛜᚧⲔᛊⳖᛊᚢꓦᚾꓦᚾⲔᚧᛜᛢᚹᚷᛜꓦᛁꓦᛁᛩⳖᚪᛁᛁᚪ"',
  '"<font color="#4948ea">Even without wings, I can still fly!</font>"',
  '"<font color="#4948ea">Watch out! You\'re gonna crash!</font>"',
  '"<font color="#4948ea">The whole city\'s on fire!</font>"',
  '"<font color="#4948ea">That tornado\'s carrying a car!</font>"',
  "Based.",
  '<a href="https://youtu.be/TKfS5zVfGBc" target="_blank">009 Sound System Dreamscape</a>',
  "get real",
  "Here. Have some choccy milk.",
  '] <font color="#29c2fe">TRANS</font> <font color="#feb2b5">RIGHTS</font> ARE <font color="#feb2b5">HUMAN</font> <font color="#29c2fe">RIGHTS</font> ]',
  'Hit the <font color="#eac0ff">Slay</font> button.',
  '"These what sir..?"',
  "Please confirm you are not a robot.",
  "And I begin to wonder.. The dreams I can't remember. When I wake in the morning - where in the world did they go?",
  '"<font color="#1baada">Wahoo!</font>"',
  "Default Dance",
  "Pump Action",
  '"I\'m a Sword of Justice!"',
  '"Haru.."',
  "Hyperlink Blocked",
  "Hi there, User is inviting you to a scheduled Zoom meeting.",
  '"One small issue. I am inside of your home."',
  '<a href="https://www.youtube.com/watch?v=0XQkpZ-lyC4" target="_blank">"Hey. No. Stop. Just calm down. Don\'t do it."</a>',
  '"I guess I needed something to keep "the Ripper" in check when I was knee-deep in bodies."',
  "All these squares make a circle.",
  '"Objection!"',
  '"Nanomachines, son. They harden in response to physical trauma."',
  '"Played college ball, ya know."',
  '"Wind blows, rain falls, and the strong prey upon the weak."',
  "You can't out pizza the hut",
  '"I think I\'m about to steal!"',
  '"Attention all Fortnite Gamers."',
  "Funky Beats",
  "I literally love Ralsei so much",
  '"Hello everyone. This is YOUR Daily Dose of Internet"',
  '"What do you mean by that?"',
  "Unity's Particle System",
  '"omg i really love your art!! ahndjdksndbdjsvshsjskskwivevwj"',
  '"Corporate America"',
  '"awww the scrunkly 🥰🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺 double tap now if you\'d scrunkly the when 😆"',
  "#screenshotsaturday  #gamedev  #madewithunity",
  '"Team Fortress 2\'s massive botting problem has made the game nigh-unplayable for two years and counting, and its community is begging Valve for answers – or at least acknowledgement."',
  '<a style="color:#f4f2af;" href="https://www.youtube.com/watch?v=n-aL5da34SI" target="_blank">"Neco-Arc"</a>',
  '"YOU\'RE GOING THE WRONG WAY"',
  '"Hello everybody, my name is Markiplier and welcome to Five Nights at Freddy\'s"',
  "JOYCON BOYZ",
  '"In the criminal justice system, sexually based offenses are considered especially heinous. In New York city, The dedicated detectives that investigate these vicious felonies are members of an elite squad known as the Special Victims Unit. These are their stories."',
  '"My name is Walter Hartwell White. I live at 308 Negra Arroyo Lane Albuquerque New Mexico 87104. This is my confession."',
  '"my brother in christ"',
  '"my sister in christ"',
  "Square one",
  "The Tale of a CRUEL WORLD",
  "\"that upsmash, oh zhu poor zhu, happy feet wombo combo, that ain't falco, that ain't falc... ohhhh x12, WHERE YOU AT????? x3, oh oh my god WOMBO COMBO!!\"",
  "Say NO to NFTS!! >:(",
  "May I interest you in some programmer socks?",
  "(uh oh!☹️) BACK TO THE LAB AGAIN! (oh no!😬) BACK TO THE LAB AGAIN! (We messed up😱) BACK TO THE LAB AGAIN! (Not again😒) BACK TO THE LAB AGAIN!🤓",
  "Nice opinion, just one tiny problem with it. Inspecting your reply, it looks like your opinion is different from mine. Let me tell you something, I am the baseline for opinions. Any opinion I hold is objectively correct and as a result, any other opinions are wrong. Guess what? You happen to hold the wrong one! I hope you know that your opinion is now illegal. I have contacted the FBI, CIA, the NSA, the navy seals, secret service, and your mom! You'll be sorry you ever shared your opinions, by the time you're reading this, you'll be done for. Nature will punish you, humanity will punish you, space will punish you. We decided just to make sure we'll nuke your house from orbit. So there's no chance you can run away, everyone will know you will die. It's a small price to pay, to remove your wrong opinion from this world.",
  "Have you heard of the critically acclaimed MMORPG Final Fantasy XIV with an EXPANDED FREE TRIAL? Which you can play through the entirety of A Realm Reborn and the award winning Heavensward Expansion up to level 60 for FREE with no restrictions on playtime.",
  '"Please stop hitting my rib cage with a metal bar!" 🤓🤓🤓',
  '"Consider the following:"',
  "This video is sponsored by Nord VPN",
  "This video is sponsored by Raycons",
  "This video is sponsored by Raid Shadow Legends",
  '"IT\'S NO USE!"',
  '"This tweet has been deleted."',
  '<a href="https://www.youtube.com/watch?v=BX2Xurh1mVc" target="_blank">"DO YOU LIKE WAFFLES?"</a>',
  '"Welcome to Team Fortress 2, after 9 years in development hopefully, it will have been worth the wait. thanks and have fun."',
  "It looks like the logo says The CABSOLUTE realm.",
  "Maybe I should consider making snapshots of my own website when it reaches a large update",
  "Aw man, the Discover Weekly just wasn't good today.",
  "Making web buttons take so much time lol",
  "I REALLY WOULD LIKE IF THE VIDEO IN THE BACKGROUND WOULD ACTUALLY PLAY ON PAGE LOAD!!",
  "I'm <strong>REALLY</strong> addicted to updating this website every day!",
  "I'm <strong>REALLY</strong> addicted to updating this website every day!",
  "I'm <strong>REALLY</strong> addicted to updating this website every day!!",
  "I'm <strong>REALLY</strong> addicted to updating this website every day!",
  "I'm <strong>REALLY</strong> addicted to updating this website every day!",
  "I'm <strong>REALLY</strong> addicted to updating this website every day!!!",
  "im doing my best",
  "<3",
  "I see you..",
  "uwu",
  "owo",
  ">w<",
  "PECK!",
  "WE'RE WORKING ON IT!!",
  '"I HAVE NO IDEA!"',
  "I see you. Yeah you. Sitting on this page.",
  "THE SONIC MANIA UI DESIGN IS SOOO COOL!!",
  "Consider doing a <font color='#f4f2af'>barrell roll!</font>",
  "Consider doing a <font color='#f4f2af'>barrell roll!</font>",
  "Consider doing a <font color='#f4f2af'>barrell roll!</font>",
  "Consider doing a <font color='#f4f2af'>barrell roll!</font>",
  "Consider doing a <font color='#f4f2af'>barrell roll!</font>",
  "polyriddim",
  "Haywyre is so cool",
  '<a href="https://www.youtube.com/watch?v=jlN2dsOZRKo" target="_blank">"How much stuff can you stuff in a stuffie till your stuffies stuffed enough stuff?"</a>',
  'AYO DO NOT TYPE <font color="#f4f2af">wii</font> ON THIS PAGE!!',
  'AYO DO NOT TYPE <font color="#f4f2af">wii</font> ON THIS PAGE!!',
  'AYO DO NOT TYPE <font color="#f4f2af">wii</font> ON THIS PAGE!!',
  'AYO DO NOT TYPE <font color="#f4f2af">wii</font> ON THIS PAGE!!',
  'AYO DO NOT TYPE <font color="#f4f2af">wii</font> ON THIS PAGE!!',
  'AYO DO NOT TYPE <font color="#f4f2af">wii</font> ON THIS PAGE!!',
  'AYO DO NOT TYPE <font color="#f4f2af">wii</font> ON THIS PAGE!!',
  "Yes, 4 tickets to the Minions: Rise Of Gru please.",
  '"Gender Dysphoria"',
  "\"Maybe I'll participate in this annual's Art Fight\"",
  "imma need a minute...",
  "SHOW ME THOSE BEANSS!!",
  "I actually enjoyed Sonic 06 as a kid",
  "THE PAC IS BACK",
  '"BRO THEY ARE LITERALLY TAKING OUR RIGHTS AWAY!!"',
  "I wonder if you've noticed that this marquee changes every time you hit the refresh button.",
  "I wonder if you've noticed that this marquee changes every time you hit the refresh button.",
  "I wonder if you've noticed that this marquee changes every time you hit the refresh button.",
  "I wonder if you've noticed that this marquee changes every time you hit the refresh button.",
  "Diane Foxington",
  '"Grass grows, birds fly, sun shines, and brotha\' - I hurt people."',
  '"LOL KAZUYA AND STEVE"',
  "Dysphoria",
  '"this website is definitely going on my resume"',
  '"rawr x3 nuzzles pounces on u uwu u so warm"',
  '"We are not the same"',
  '"The ship dynamic"',
  "Full of Pilk",
  "you can do it!",
  "i believe in you!",
  '"Despite Everything, It\'s Still You."',
  "\"You've met with a terrible fate, haven't you?\"",
  '"Every journey begins with a <font color="red">choice!</font>"',
  'Go follow my <a color="#f59c32" href="https://neocities.org/site/theabsoluterealm">neocities page</a> ;3',
  'Go follow my <a color="#f59c32" href="https://neocities.org/site/theabsoluterealm">neocities page</a> ;3',
  'Go follow my <a color="#f59c32" href="https://neocities.org/site/theabsoluterealm">neocities page</a> ;3',
  "This baked logo above me is going to bug me forever",
  "'myspace'",
  '"Don\'t worry, this is fully paid internship."',
  "Cancelled",
  "Monstercat",
  "NEVER give up!!",
  "I'm so proud of you!!",
  "keep it PLURR ^3^",
  'Listen to 2010 Toyota Corolla by 2003 Toyota Corolla on <a href="https://open.spotify.com/track/2vhPKZS80ap76Mk6DtVyXZ?si=91ea8a9b42414133" color="#1ed760">Spotify</a>',
  "Stabilizing as best as possible almost everyday!",
  "corvid",
  '"Always 6 feet away!"',
  "Maybe the thought of adding the youtube channel was not a good idea",
  "Busy dying at band practice",
  "Hey hey! how are you doing today?",
  "the curse of creating 8 bar loops every time you get in the studio",
  '"what is an eq?"',
  '"i think it just needs a soundgoodizer"',
  '"I would like to thank In The Mix"',
  "Emma Essex is really cool",
  "rupurudu",
  '"just block dude its not that hard"',
  '"this behavior looks very unhealthy"',
  '"twitter"',
  'go read <a href="https://twitter.com/i/events/1416629163725770757?s=20"><font color="#70cdcd">duncan</font> & <font color="#f5b781">eddie</font> by doginacafe</a> <3',
  "chester",
  "HOW DOES CAMELLIA DO IT?!?!",
  "i hope all these elements on screen aren't making you lag right now",
  "rip support for internet explorer 6/15/2022",
  "when being a band student takes most of your college life",
  "I LOVE TAKING SO MUCH POWER IN MY SCHOOL APARTMENT!!",
  '"hit the floor"',
  '"Congratulations, and welcome to the Get Strong Crew"',
  "there are so many updates to be made here.. its im gonna be updating this website forever! not saying I have a problem with that <3",
  'Personally, my favorite theme is <a style="color: #76d493" id="theme" onclick="setTheme(\'alien\')">Alien</a>',
  'Personally, my favorite theme is <a style="color: #76d493" id="theme" onclick="setTheme(\'alien\')">Alien</a>',
  'Personally, my favorite theme is <a style="color: #76d493" id="theme" onclick="setTheme(\'alien\')">Alien</a>',
  'Personally, my favorite theme is <a style="color: #76d493" id="theme" onclick="setTheme(\'alien\')">Alien</a>',
  "Just to let you know, this website has only been tested on two computers, an ipad, and iphone.",
  '"Ya like jazz?"',
  '"What Are You Doing in My Swamp?"',
  '<a href="https://youtu.be/kPE7ZCGjw4o">"Grand, Central station- It\'s Grand, and it\'s Central!"</a>',
  "They don't know...",
  "Yes, I know this page looks COMPLETELY DIFFERENT from the index page. Dont't worry though, I'm working VERY HARD on the theme",
  "Yes, I know this page looks COMPLETELY DIFFERENT from the index page. Dont't worry though, I'm working VERY HARD on the theme",
  "Yes, I know this page looks COMPLETELY DIFFERENT from the index page. Dont't worry though, I'm working VERY HARD on the theme",
  "Yes, I know this page looks COMPLETELY DIFFERENT from the index page. Dont't worry though, I'm working VERY HARD on the theme",
  "A <a style='color:#15456a' onclick=\"openPop('assets/stickernew.png')\">QR code</a> leading to this website is on several stickers I placed around my campus! Maybe, but hopefully, I can place them elsewhere besides my campus!",
  "A <a style='color:#15456a' onclick=\"openPop('assets/stickernew.png')\">QR code</a> leading to this website is on several stickers I placed around my campus! Maybe, but hopefully, I can place them elsewhere besides my campus!",
  "A <a style='color:#15456a' onclick=\"openPop('assets/stickernew.png')\">QR code</a> leading to this website is on several stickers I placed around my campus! Maybe, but hopefully, I can place them elsewhere besides my campus!",
  "A <a style='color:#15456a' onclick=\"openPop('assets/stickernew.png')\">QR code</a> leading to this website is on several stickers I placed around my campus! Maybe, but hopefully, I can place them elsewhere besides my campus!",
  "A <a style='color:#15456a' onclick=\"openPop('assets/stickernew.png')\">QR code</a> leading to this website is on several stickers I placed around my campus! Maybe, but hopefully, I can place them elsewhere besides my campus!",
  "A <a style='color:#15456a' onclick=\"openPop('assets/stickernew.png')\">QR code</a> leading to this website is on several stickers I placed around my campus! Maybe, but hopefully, I can place them elsewhere besides my campus!",
  "A <a style='color:#15456a' onclick=\"openPop('assets/stickernew.png')\">QR code</a> leading to this website is on several stickers I placed around my campus! Maybe, but hopefully, I can place them elsewhere besides my campus!",
  "It seems as if im polishing this site more than adding the actual content",
  '"My honest reaction to that information:"',
  "Have you seen the Paw Patrol movie?",
  "GOD IM SOOO BUSY ALL THE TIME!!!",
  "IM WORKING AS HARD AS I CAN I SWEAR!!",
  "so many responsibilities Dx",
  "give me a break",
  "my sincerest reaction",
  "CAN WE GET MUCH HIGHER",
  "<a href='https://youtu.be/wKTHkHtwZP8'>I'M NOT GONNA SUGARCOAT IT</a>",
  "im so tired of school please help me",
  "a page without an ABOUT ME PAGE??? WHAT AM I DOING??!",
  "nah dude",
  "nya~",
  "there is a pipebomb at your doorstep",
  "?",
  "ENBY GANG!!",
  '"okay thats cool, but how are you going to make money with it?"',
  "i got a bit silly..",
  "sick and tired of fighting me and everyone else in me",
  "dream big pal!",
  "im so exhausted",
  "the lore",
  "when it becomes hard to live",
  "IM SO FULL OF DEPRESSION YUM",
  "we'll pull through this together!",
  "i fight for my friends",
  "i picture the world in a fantasy land, its almost like i have pyrovision goggles on the moment i wake up every morning!",
  "YEAH WE GAY, KEEP SCROLLING",
  "nah, you cannot change me. im not fitting into society anymore",
  "me thinking this page is very polished",
  "did you know that when i first started this website, you were rendering the logo's gif in 2k res but it's intrinstic/simulated size was 860px? no wonder why there were performance issues!!",
  "those of you all that saved my page on the <a style='color:#ab2e33' href='https://web.archive.org/web/20220000000000*/https://theabsoluterealm.com/'>Wayback Machine</a> when i was first developing it, i love you",
  "cringe culture is dead. draw what makes you happy!!",
  "im scared to make my entire site javascript heavy just because for compatibility reasons",
  "did you really think the index was going to be the same as the main page? i thought that too a few times lol",
  '"please stop GA\'ing everything, thanks."',
  "mann.. do yall remember fusionfall?",
  "Have you heard of <a href='https://battleofthebits.org/'>Battle of the Bits</a>?",
  "Have you tried the Freedom Planet series? It's so awesome!",
  '"Removed Herobrine"',
  "Clutch or Kick",
  "Excuse me, lemme go ahead and hit that dribble to wall to musty flick 11x flip reset backboard quadruple tap goal.",
  '"There\'s a snake in my boot!"',
  '"Lemme see them grippers"',
  '"What was he cooking?"',
  '"Does he know?"',
  "Hot Topic",
  '"IM THE BIGGEST BIRD"',
  "play TUNIC.",
  "wym no?",
  "Yeah, im against the AI artwork",
  "Um, this is a wendy's.",
  "the secret formula",
  "What are you talking about? We are literally inside a mcdonalds sprite",
  "Little do they know..",
  "This is a safe place for bears!",
  "Strugglers welcome!",
  "Let me do it for you",
  "Check out Salty Bets!",
  "analytics by GoatCounter!",
  "Hosted by neocities!",
  "1738",
  "Who farted",
  "Mr. Beast",
  "TELL ME ABOUT YOUR FURSONA!!!",
  "This dude CANNOT be for real",
  "Consider merging those duped nearby verticies.",
  "GO PLAY HI-FI RUSH!!",
  "GRRREETINGS",
  "THIS ONE'S FOR YOU!",
  '"wait, you actually study?"',
  "my god drawing is so hard",
  "wanna play rocket league?",
  "WATCH BLUEY",
  "you like kissing men don't you",
  "you like kissing women don't you",
  '"Who is your favorite fearless hero?"',
  "Wort, wort, wort!",
  "Your Only Move Is HUSTLE",
  "You will be moved to team BLU in 5 seconds if the teams are still not balanced.",
  "You will be moved to team RED in 5 seconds if the teams are still not balanced.",
  "And yet here we are.",
  "infused with evil thoughts",
  "a mere skill issue",
  "what has roblox become these days",
  "this page got referred on 4chan!",
  '"Unlicensed apps have been disabled. Get genuine Adobe apps"',
  '"Adobe Genuine Service Alert"',
  'Go listen to <a style="color: #e5b95a;" href="https://soundcloud.com/tancla">Tancla</a>!',
  "If something seems strange or broken on the page, consider doing Ctrl+Shift+R to do a Cache Reset/Hard Reload!",
  '"Ugh, here they go talking about that blockchain crap again -_-"',
  "Updating this entire website is so slow because I prioritize responsiveness unfortunately",
  "WHAT IS THAT MELODY?!",
  '"This is trifficult!"',
  '"I slipped on ma\' beans!"',
  "Now do it while facing left.",
  "For real life?",
  "I HAVE A PROBLEMATIC OBSESSION WITH BLUEY",
  "ITS PISSSSSSSSSSSSSSSSSS",
  "Remove stems from sprout, cut in half, remove outer leaves, mix in desired bacon fat and salt/pepper, and cook at 350F until roasted, portion 8oz into 12oz rarebits.",
  '"The Sizzle" ™',
  'Have yall played <a href="https://www.roblox.com/games/11318993628/">Merc Fleet? It\'s sooo fun!!</a>',
  "Nah, imma do my own thing.",
  "\"Don't worry he don't bite\"",
  "Really wish I had a backend server",
  "I WISH I HAD MY OWN HOME SERVER",
  "IF ANYONE IS OUT THERE KNOWING AND WILLING TO TEACH ME MAKE A HOME SERVER WITH YOUR OLD PC PLEASE TELL ME IM SO STUPID",
  "ON DAY " +
    Math.ceil((new Date() - new Date("2024-01-02")) / (1000 * 3600 * 24)) +
    " OF ESTROGEN HRT BABY!!",
];

document.querySelector("marquee").innerHTML =
  phrase[Math.floor(Math.random() * phrase.length)];
